# Generated by Django 5.2.14 on 2026-05-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado_operativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_sistema', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='activos.activo', verbose_name='Activo Asociado')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='SubSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsistemas', to='activos.sistema')),
            ],
            options={
                'verbose_name': 'Subsistema',
                'verbose_name_plural': 'Subsistemas',
            },
        ),
    ]
