# Generated by Django 5.2.14 on 2026-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=100)),
                ('sistema_activo', models.CharField(max_length=100)),
                ('subsistema_activo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('repuestos_necesarios', models.TextField()),
                ('criticidad', models.IntegerField(choices=[(1, '1 - Baja'), (2, '2 - Media'), (3, '3 - Alta'), (4, '4 - Crítica'), (5, '5 - Emergencia')], default=1, max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('trabajo_realizado', models.TextField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
