# Generated by Django 5.2.14 on 2026-05-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=100)),
                ('sistemaActivo', models.CharField(max_length=100)),
                ('subsistemaActivo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('repuestosNecesarios', models.TextField()),
                ('criticidad', models.CharField(choices=[(1, '1 - Muy baja'), (2, '2 - Baja'), (3, '3 - Media'), (4, '4 - Alta'), (5, '5 - Crítica')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('fechaCierre', models.DateTimeField(blank=True, null=True)),
                ('trabajoRealizado', models.TextField(blank=True, null=True)),
                ('observacionesCierre', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
