# Generated by Django 5.2.14 on 2026-05-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='activos.activo', verbose_name='Activo Afectado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='componente_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='activos.componente', verbose_name='Componente Afectado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sistema_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='activos.sistema', verbose_name='Sistema Afectado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='solicitudes.solicitud'),
        ),
    ]
