# Generated by Django 5.2.14 on 2026-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='criticidad',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica'), (5, 'Emergencia')], default=1),
        ),
    ]
