# Generated by Django 5.2.14 on 2026-08-08 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'La descripción debe tener al menos 30 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='titulo',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(15, 'El título debe tener al menos 15 caracteres.')]),
        ),
    ]
