# Generated by Django 5.2.14 on 2026-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_criticidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
