# Generated by Django 5.2.14 on 2026-05-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='solicitudes.solicitud'),
        ),
    ]
