# Generated by Django 5.2.14 on 2026-05-26 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_seguimiento_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_realizados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
